"""A tile is offered only if the hardware says it can hold it.

A user evaluating 0.5.3 on two A40s (sm_86) could not run a single language
model on the Triton branch: `flash_attention_forward_kernel` asked for 164 352
bytes of shared memory per block where the card's limit is 101 376. The number
was identical in both Triton modes and did not move with sequence length, which
is the signature of a tile chosen from constants rather than derived from the
shape.

The cause, found 2026-09-10, in three places:

  * `kernels/wrappers.py:8383` — the tile is chosen on `_NBX_HAS_NATIVE_BF16`,
    a flag that separates Volta from Ampere and says nothing else. sm_86 has
    native bf16, so it takes the branch written for sm_80 and gets BLOCK_M=128.
    The comment there reads "Ampere+ keeps 128" — but sm_80 declares 163 KB of
    shared memory per block and sm_86 declares 99.
  * `kernels/ops/_configs.py::sdpa_block_ceiling` — the clamp that would have
    caught it reads `sdpa_thresholds` from the vendor profile. The profile the
    engine generated for this unknown card has no such row, so the clamp
    returned `(None, None)` and clamped nothing.
  * `kernels/ops/_configs.py::arch_smem_budget` — the budget itself is read
    from a YAML table keyed by compute capability, with a fallback to the
    capability MAJOR. Its own docstring names the victims: "a T4 (7.5), an A10
    or 3090 (8.6) and an L4 or 4090 (8.9) would resolve to no profile". sm_86
    therefore inherits the A100's 163 KB.

The engine already wrote `compute_capability: '8.6'` into the profile it
generated by itself for that card. The information was present and unused.

This file pins the PREDICATE, which is what can be exercised without the
hardware: given a device budget and a cost for each candidate tile, the
selector must refuse the tile that cannot fit and return one that can. The cost
function is injected on purpose — the real one asks the compiler what it
compiled, because an analytic formula for a Triton kernel's shared memory is a
guess, and pruning on a guessed budget deletes working configurations.

Run: PYTHONPATH=src python -m pytest tests/unit/kernels/test_tile_fits_the_declared_smem.py
"""
from __future__ import annotations

import pytest

# Per-block shared-memory ceilings, bytes. Sources: NVIDIA CUDA C Programming
# Guide, Table 15 "Technical Specifications per Compute Capability" (maximum
# amount of shared memory per thread block), cross-checked against the
# per-architecture tuning guides.
SMEM = {
    "7.0": 96 * 1024,      # Volta
    "7.5": 64 * 1024,      # Turing
    "8.0": 163 * 1024,     # Ampere datacenter (A100)
    "8.6": 99 * 1024,      # Ampere consumer/professional (A40, A10, 3090)
    "8.9": 99 * 1024,      # Ada
    "9.0": 227 * 1024,     # Hopper
    "10.0": 227 * 1024,    # Blackwell datacenter
    "12.0": 99 * 1024,     # Blackwell consumer
}

# The tile the A40 report was killed by, and what it costs.
TOO_BIG = (128, 64)
FITS = (64, 64)
COST = {(128, 64): 164_352, (64, 64): 82_176, (32, 64): 41_088}


def _cost(tile):
    return COST[tile]


def test_the_tile_that_killed_the_a40_is_refused_on_its_own_budget():
    from neurobrix.kernels.ops._configs import largest_tile_within_smem

    got = largest_tile_within_smem([TOO_BIG, FITS], _cost, SMEM["8.6"])
    assert got != TOO_BIG, (
        f"{TOO_BIG} costs {COST[TOO_BIG]} bytes and sm_86 declares "
        f"{SMEM['8.6']} — it must not be offered")
    assert _cost(got) <= SMEM["8.6"]


def test_the_same_tile_is_kept_where_the_hardware_holds_it():
    """sm_80 declares 163 KB and does hold it. The fix must not cost the A100
    its tile — a ceiling that clamps everywhere is a regression, not a guard."""
    from neurobrix.kernels.ops._configs import largest_tile_within_smem

    assert largest_tile_within_smem([TOO_BIG, FITS], _cost, SMEM["8.0"]) == TOO_BIG
    assert largest_tile_within_smem([TOO_BIG, FITS], _cost, SMEM["9.0"]) == TOO_BIG


def test_every_ceiling_gets_a_tile_that_fits_it():
    """Nine families, one predicate. A tile is offered only where it fits."""
    from neurobrix.kernels.ops._configs import largest_tile_within_smem

    candidates = [(128, 64), (64, 64), (32, 64)]
    for cap, budget in SMEM.items():
        got = largest_tile_within_smem(candidates, _cost, budget)
        assert _cost(got) <= budget, (
            f"capability {cap} declares {budget} bytes and the selector "
            f"offered {got} at {_cost(got)}")


def test_an_unknown_budget_changes_nothing():
    """None means the hardware did not say. Pruning on a guessed budget deletes
    working configurations — the caller keeps its own proposal."""
    from neurobrix.kernels.ops._configs import largest_tile_within_smem

    assert largest_tile_within_smem([TOO_BIG, FITS], _cost, None) == TOO_BIG


def test_the_space_is_never_emptied():
    """When nothing fits, the smallest is returned rather than nothing: an
    empty selection is a crash, and a tile that spills is at least measurable."""
    from neurobrix.kernels.ops._configs import largest_tile_within_smem

    got = largest_tile_within_smem([TOO_BIG, FITS], _cost, 1024)
    assert got == FITS
