"""A pickled constant in two graphs is the same constant when its VALUES are, whatever bytes
each torch wrote.

TinyLlama re-traced on the engine environment (torch 2.14) against its July container (torch
2.5): every rotary table's `constant_data` differed as bytes and matched as values, and the
gate counted each as a difference beyond the annotation. The two fixtures below are that very
tensor — `block.9.attn.rotary_embed.inv_freq`, 32 bfloat16 values — as torch 2.5.1 (ml/venv)
and torch 2.14.0 (nbx_t214) pickled it from the SAME Forge on 2026-09-26 04:26 UTC. Seen RED on
retrace-2026-09-26 a7d62766 (bytes compared).
Run: python -m pytest tests/unit/tools/test_retrace_gate_compares_a_constant_by_value.py
"""
from __future__ import annotations

import base64
import io
import sys
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "tools"))
import retrace_zoo as R  # noqa: E402

INV_FREQ_TORCH_2_5 = "UEsDBAAACAgAAAAAAAAAAAAAAAAAAAAAAAAQABIAYXJjaGl2ZS9kYXRhLnBrbEZCDgBaWlpaWlpaWlpaWlpaWoACY3RvcmNoLl91dGlscwpfcmVidWlsZF90ZW5zb3JfdjIKcQAoKFgHAAAAc3RvcmFnZXEBY3RvcmNoCkJGbG9hdDE2U3RvcmFnZQpxAlgBAAAAMHEDWAMAAABjcHVxBEsgdHEFUUsASyCFcQZLAYVxB4ljY29sbGVjdGlvbnMKT3JkZXJlZERpY3QKcQgpUnEJdHEKUnELLlBLBwhOoMUamQAAAJkAAABQSwMEAAAICAAAAAAAAAAAAAAAAAAAAAAAABEAKABhcmNoaXZlL2J5dGVvcmRlckZCJABaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpsaXR0bGVQSwcIhT3jGQYAAAAGAAAAUEsDBAAACAgAAAAAAAAAAAAAAAAAAAAAAAAOAD4AYXJjaGl2ZS9kYXRhLzBGQjoAWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWoA/QD8QP9g+oj5zPjY+CT7NPZo9Zj0tPQI9wjySPFo8JDz2O7g7ijtPOxs76TqvOoM6RToTOt05pjl5OTo5DDlQSwcIxvcW+EAAAABAAAAAUEsDBAAACAgAAAAAAAAAAAAAAAAAAAAAAAAPAEMAYXJjaGl2ZS92ZXJzaW9uRkI/AFpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWjMKUEsHCNGeZ1UCAAAAAgAAAFBLAwQAAAgIAAAAAAAAAAAAAAAAAAAAAAAAHgAyAGFyY2hpdmUvLmRhdGEvc2VyaWFsaXphdGlvbl9pZEZCLgBaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaMDU3Njg1ODg1NzM4NTk5NjI3ODIwMDAwMDgyOTEwNjUxMzU5ODYxNFBLBwjd5sn3KAAAACgAAABQSwECAAAAAAgIAAAAAAAATqDFGpkAAACZAAAAEAAAAAAAAAAAAAAAAAAAAAAAYXJjaGl2ZS9kYXRhLnBrbFBLAQIAAAAACAgAAAAAAACFPeMZBgAAAAYAAAARAAAAAAAAAAAAAAAAAOkAAABhcmNoaXZlL2J5dGVvcmRlclBLAQIAAAAACAgAAAAAAADG9xb4QAAAAEAAAAAOAAAAAAAAAAAAAAAAAFYBAABhcmNoaXZlL2RhdGEvMFBLAQIAAAAACAgAAAAAAADRnmdVAgAAAAIAAAAPAAAAAAAAAAAAAAAAABACAABhcmNoaXZlL3ZlcnNpb25QSwECAAAAAAgIAAAAAAAA3ebJ9ygAAAAoAAAAHgAAAAAAAAAAAAAAAACSAgAAYXJjaGl2ZS8uZGF0YS9zZXJpYWxpemF0aW9uX2lkUEsGBiwAAAAAAAAAHgMtAAAAAAAAAAAABQAAAAAAAAAFAAAAAAAAAEIBAAAAAAAAOAMAAAAAAABQSwYHAAAAAHoEAAAAAAAAAQAAAFBLBQYAAAAABQAFAEIBAAA4AwAAAAA="
INV_FREQ_TORCH_2_14 = "UEsDBAAACAgAAAAAAAAAAAAAAAAAAAAAAAAQABIAYXJjaGl2ZS9kYXRhLnBrbEZCDgBaWlpaWlpaWlpaWlpaWoACY3RvcmNoLl91dGlscwpfcmVidWlsZF90ZW5zb3JfdjIKcQAoKFgHAAAAc3RvcmFnZXEBY3RvcmNoCkJGbG9hdDE2U3RvcmFnZQpxAlgBAAAAMHEDWAMAAABjcHVxBEsgdHEFUUsASyCFcQZLAYVxB4ljY29sbGVjdGlvbnMKT3JkZXJlZERpY3QKcQgpUnEJdHEKUnELLlBLBwhOoMUamQAAAJkAAABQSwMEAAAICAAAAAAAAAAAAAAAAAAAAAAAABcAIgBhcmNoaXZlLy5mb3JtYXRfdmVyc2lvbkZCHgBaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWloxUEsHCLfv3IMBAAAAAQAAAFBLAwQAAAgIAAAAAAAAAAAAAAAAAAAAAAAAGgA3AGFyY2hpdmUvLnN0b3JhZ2VfYWxpZ25tZW50RkIzAFpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWjY0UEsHCD93cekCAAAAAgAAAFBLAwQAAAgIAAAAAAAAAAAAAAAAAAAAAAAAEQA/AGFyY2hpdmUvYnl0ZW9yZGVyRkI7AFpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpabGl0dGxlUEsHCIU94xkGAAAABgAAAFBLAwQAAAgIAAAAAAAAAAAAAAAAAAAAAAAADgA+AGFyY2hpdmUvZGF0YS8wRkI6AFpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlqAP0A/ED/YPqI+cz42Pgk+zT2aPWY9LT0CPcI8kjxaPCQ89ju4O4o7TzsbO+k6rzqDOkU6EzrdOaY5eTk6OQw5UEsHCMb3FvhAAAAAQAAAAFBLAwQAAAgIAAAAAAAAAAAAAAAAAAAAAAAADwBDAGFyY2hpdmUvdmVyc2lvbkZCPwBaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlozClBLBwjRnmdVAgAAAAIAAABQSwMEAAAICAAAAAAAAAAAAAAAAAAAAAAAAB4AMgBhcmNoaXZlLy5kYXRhL3NlcmlhbGl6YXRpb25faWRGQi4AWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWjE1NzI4MTk5NTExODU0NjQzMDI2MDM1MDQ0MjU4NzE3NjI2NDg1NDVQSwcITK36vigAAAAoAAAAUEsBAgAAAAAICAAAAAAAAE6gxRqZAAAAmQAAABAAAAAAAAAAAAAAAAAAAAAAAGFyY2hpdmUvZGF0YS5wa2xQSwECAAAAAAgIAAAAAAAAt+/cgwEAAAABAAAAFwAAAAAAAAAAAAAAAADpAAAAYXJjaGl2ZS8uZm9ybWF0X3ZlcnNpb25QSwECAAAAAAgIAAAAAAAAP3dx6QIAAAACAAAAGgAAAAAAAAAAAAAAAABRAQAAYXJjaGl2ZS8uc3RvcmFnZV9hbGlnbm1lbnRQSwECAAAAAAgIAAAAAAAAhT3jGQYAAAAGAAAAEQAAAAAAAAAAAAAAAADSAQAAYXJjaGl2ZS9ieXRlb3JkZXJQSwECAAAAAAgIAAAAAAAAxvcW+EAAAABAAAAADgAAAAAAAAAAAAAAAABWAgAAYXJjaGl2ZS9kYXRhLzBQSwECAAAAAAgIAAAAAAAA0Z5nVQIAAAACAAAADwAAAAAAAAAAAAAAAAAQAwAAYXJjaGl2ZS92ZXJzaW9uUEsBAgAAAAAICAAAAAAAAEyt+r4oAAAAKAAAAB4AAAAAAAAAAAAAAAAAkgMAAGFyY2hpdmUvLmRhdGEvc2VyaWFsaXphdGlvbl9pZFBLBgYsAAAAAAAAAB4DLQAAAAAAAAAAAAcAAAAAAAAABwAAAAAAAADPAQAAAAAAADgEAAAAAAAAUEsGBwAAAAAHBgAAAAAAAAEAAABQSwUGAAAAAAcABwDPAQAAOAQAAAAA"


def _pickled(t):
    buf = io.BytesIO()
    torch.save(t, buf)
    return base64.b64encode(buf.getvalue()).decode()


def test_the_same_tensor_pickled_by_two_torches_is_equal():
    assert INV_FREQ_TORCH_2_5 != INV_FREQ_TORCH_2_14
    assert R.constants_equal(INV_FREQ_TORCH_2_5, INV_FREQ_TORCH_2_14)


def test_different_values_or_dtypes_or_shapes_differ():
    t = torch.load(io.BytesIO(base64.b64decode(INV_FREQ_TORCH_2_14)), weights_only=True)
    assert not R.constants_equal(_pickled(t), _pickled(t + 1))
    assert not R.constants_equal(_pickled(t), _pickled(t.float()))
    assert not R.constants_equal(_pickled(t), _pickled(t[:16]))
    assert not R.constants_equal(_pickled(t), None) and not R.constants_equal("not base64!", _pickled(t))
